### ISSUE TITLE
calendar popup is behind semantic-ui react modal

### ISSUE THREAD

**Issue by ayanez17** [arfedulov/semantic-ui-calendar-react#26] opened 2018-08-14 16:02 UTC
![image](https://user-images.githubusercontent.com/18299052/44103814-33330a36-9fbb-11e8-8052-6ff49b071bff.png)

I have a modal from semantic UI react. Within that modal there is a form and within that form there is this:
```
 <DateTimeInput
    fluid
    label='Time and Date'
    name="dateTime"
    placeholder="Date Time"
    value={this.state.dateTime}
    iconPosition="left"
    onChange={this.handleChange} />
```
The issue is that the calendar popup appears below (behind) the modal and is not useable. I have tried changing the zindex of the DateTimeInput but it doesn't seem to work.

**Comment by arfedulov** [comment] 2018-08-14 18:04
I could't reproduce this bug. Could you please provide version number of these packages: 

* semantic-ui-react
* semantic-ui-css
* semantic-ui-calendar-react

**Comment by ayanez17** [comment] 2018-08-14 18:12
Here you go:
```
    "semantic-ui-calendar-react": "^0.8.0",
    "semantic-ui-css": "^2.3.2",
    "semantic-ui-react": "^0.78.3",
```

**Comment by arfedulov** [comment] 2018-08-14 19:32
I still couldn't reproduce it. I'm not sure it's something in calendar causes this issue. I'm currently in refactoring the package, though. I'll get rid of unnecessary complexity in it and will change probably how it deals with Popup. So let's see what we will have after I release it.

**Comment by ayanez17** [comment] 2018-08-14 19:58
I found the issue. In the semantic-ui-react Modal I had attribute 
`dimmer= {'blurring'}`
Once I removed that, the calendar worked as intended.

**Comment by arfedulov** [comment] 2018-08-14 20:06
Cool, I think we can close the issue.

**Closed** 2018-08-14 20:08 UTC

**Comment by ayanez17** [comment] 2018-08-14 20:27
FYI: https://github.com/Semantic-Org/Semantic-UI-React/issues/1803
