### ISSUE TITLE
Popup opens in top left corner

### ISSUE THREAD

**Issue by tomitrescak** [arfedulov/semantic-ui-calendar-react#162] opened 2019-06-18 14:03 UTC
**Describe the bug**

chekc out following gif. The popup opens in the top left part of the window and then "jumps" to its position.

![ReactBug](https://user-images.githubusercontent.com/2682705/59690900-77335500-91e2-11e9-8242-e63263f8fd88.gif)

**Expected behavior**
opens where the input it

**Dependencies versions**
Provide version numbers of following packages:

* semantic-ui-react - 0.87.1
* semantic-ui-css (or any alternative) -2.4.1
* semantic-ui-calendar-react - 0.15.0

**Comment by loxs** [comment] 2019-06-19 08:21
Yup, happens here too. Only introduced with the latest release.

**Comment by loxs** [comment] 2019-06-19 08:30
Actually it seems to be because of a change in `semantic-ui-react` itself. Downgrading to `0.86.0` is a workaround

**Comment by zheyujie** [comment] 2019-06-21 03:11
Setting animation='none' is another workaround
Duplicate of #152

**Closed** 2019-06-21 11:05 UTC
